### ISSUE TITLE
Buat file index.css

### ISSUE THREAD

**Issue by dmtrxw** [dmtrxw/git-exercise#7]
Buat file `index.css` dengan isi:
```css
* {
  margin: 0;
  padding: 0;
}
```
